config/routes.rb
Rails.application.routes.draw do
  root to: "job_candidates#index" #index path
  resources :job_candidates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_language.rb
class CandidateLanguage < ApplicationRecord
  belongs_to :job_candidate
  belongs_to :programming_language
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods

    def filter(params)
      if params["search"]
        filter = params["search"]["name"]
        results = self.candidate_search("#{filter}")
      else
        results = self.all
      end
      results
    end

  end
end

app/models/job_candidate.rb
class JobCandidate < ApplicationRecord
  has_one_attached :resume
  has_many :candidate_languages, dependent: :destroy
  has_many :programming_languages, through: :candidate_languages

  validate :correct_document_mime_type

  include PgSearch::Model
  include Filterable

  pg_search_scope :candidate_search, associated_against: {
                    programming_languages: [:title]
                  },
                  using: {
                      tsearch: {prefix: true}
                  }

  private

  def correct_document_mime_type
    if resume.attached? && !resume.content_type.in?(%w(application/vnd.openxmlformats-officedocument.wordprocessingml.document application/pdf))
      errors.add(:document, 'Must be a PDF or a DOC file')
    end
  end

end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord

  has_many :candidate_languages
  has_many :job_candidates, through: :candidate_languages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/job_candidates.rb
module JobCandidates
  extend ActiveSupport::Concern

  def self.add_search_tech(job_candidate)
    if job_candidate.resume.attached? && job_candidate.resume.content_type.in?(%w(application/pdf))

      File.open(ActiveStorage::Blob.service.path_for(job_candidate.resume.key), "rb") do |io|
        reader = PDF::Reader.new(io)
        reader.pages.each do |page|
          candidate_resume = page.text.to_s
          ProgrammingLanguage.all.each do |lang|
            if candidate_resume.downcase.include? lang.title.downcase
              job_candidate.programming_languages << lang
              job_candidate.save
            end
          end
        end
      end

    elsif job_candidate.resume.attached? && job_candidate.resume.content_type.in?(%w(application/vnd.openxmlformats-officedocument.wordprocessingml.document))

      doc = Docx::Document.open(ActiveStorage::Blob.service.path_for(job_candidate.resume.key))
      doc.paragraphs.each do |page|
        candidate_resume = page.text.to_s
        ProgrammingLanguage.all.each do |lang|
          if candidate_resume.downcase.include? lang.title.downcase
            job_candidate.programming_languages << lang
            job_candidate.save
          end
        end
      end

    else

    end
  end
end

app/controllers/job_candidates_controller.rb
class JobCandidatesController < ApplicationController
  before_action :set_job_candidate, only: [:show, :edit, :update, :destroy]

  # GET /job_candidates
  # GET /job_candidates.json
  def index
    @job_candidates = JobCandidate.filter(params).paginate(page: params[:page], per_page: 9)
  end

  # GET /job_candidates/1
  # GET /job_candidates/1.json
  def show
  end

  # GET /job_candidates/new
  def new
    @job_candidate = JobCandidate.new
  end

  # GET /job_candidates/1/edit
  def edit
  end

  # POST /job_candidates
  # POST /job_candidates.json
  def create
    @job_candidate = JobCandidate.new(job_candidate_params)

    respond_to do |format|
      if @job_candidate.save

        JobCandidates.add_search_tech(@job_candidate)

        format.html { redirect_to @job_candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @job_candidate }
      else
        format.html { render :new }
        format.json { render json: @job_candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_candidates/1
  # PATCH/PUT /job_candidates/1.json
  def update
    respond_to do |format|
      if @job_candidate.update(job_candidate_params)
        format.html { redirect_to @job_candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_candidate }
      else
        format.html { render :edit }
        format.json { render json: @job_candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_candidates/1
  # DELETE /job_candidates/1.json
  def destroy
    @job_candidate.destroy
    respond_to do |format|
      format.html { redirect_to job_candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_candidate
      @job_candidate = JobCandidate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_candidate_params
      params.require(:job_candidate).permit(:name, :age, :current_address, :email, :phone_number, :resume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_candidates_helper.rb
module JobCandidatesHelper
end

app/views/job_candidates/_candidate.html.erb
<% candidates.each do |job_candidate| %>

  <div class="col-xs-4 col-sm-4">
    <div class="box-part">

      <div class="title text-center">
        <h4><%= job_candidate.name %></h4>
      </div>

      <div class="text text-center">
        <span><%= job_candidate.age %></span>
      </div>

      <div class="text text-center">
        <span><%= job_candidate.current_address %></span>
      </div>

      <div class="text text-center">
        <span><%= job_candidate.email %></span>
      </div>

      <div class="text text-center">
        <span><%= job_candidate.phone_number %></span>
      </div>

      <td><%= link_to 'Show', job_candidate %></td>
      <td><%= link_to 'Edit', edit_job_candidate_path(job_candidate) %></td>
      <td><%= link_to 'Destroy', job_candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    </div>
  </div>

<% end %>

app/views/job_candidates/_filter.html.erb
<%= simple_form_for :search, url: root_path, method: "GET" do |f| %>
  <span>
    <div class="input-group" >
       <%= f.input :name, id: "name", :input_html => { :class => "search-bar" }, label: false, placeholder: 'search' %>
       <i class="fa fa-search icon-search"></i>
           <%= f.submit 'Search', class: "btn btn-success search-button" %>
    </div>
       <a href="#" class="reset">reset</a>
    <%= link_to 'New Job Candidate', new_job_candidate_path, style: 'float: right', class: 'btn btn-primary' %>
  </span>
<% end %>

app/views/job_candidates/_form.html.erb
<%= form_with(model: job_candidate, local: true) do |form| %>
  <% if job_candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_candidate.errors.count, "error") %> prohibited this job_candidate from being saved:</h2>

      <ul>
      <% job_candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :current_address %>
    <%= form.text_field :current_address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%= form.file_field :resume %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_candidates/edit.html.erb
<h1>Editing Job Candidate</h1>

<%= render 'form', job_candidate: @job_candidate %>

<%= link_to 'Show', @job_candidate %> |
<%= link_to 'Back', job_candidates_path %>

app/views/job_candidates/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
  <div class="container">
    <div>
      <%= render "filter" %>
    </div>
    <div class="row" id="products">
      <%= render "candidate", candidates: @job_candidates %>
    </div>
    <div class="shop_pagination">
      <div class="page_info">
        <%= page_entries_info @job_candidates %>
      </div>
      <%= will_paginate @job_candidates, :container => false %>
    </div>
  </div>
</div>



<br>

app/views/job_candidates/new.html.erb
<h1>New Job Candidate</h1>

<%= render 'form', job_candidate: @job_candidate %>

<%= link_to 'Back', job_candidates_path %>

app/views/job_candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job_candidate.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @job_candidate.age %>
</p>

<p>
  <strong>Current address:</strong>
  <%= @job_candidate.current_address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_candidate.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @job_candidate.phone_number %>
</p>

<%= link_to @job_candidate.resume.filename, rails_blob_path(@job_candidate.resume, disposition: "attachment") %>

<%= link_to 'Edit', edit_job_candidate_path(@job_candidate) %> |
<%= link_to 'Back', job_candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candidate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>